
package guis;

/**
 *
 * @author arthu
 */
public class MenuPrincipalFuncionario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalFuncionario.class.getName());

    /**
     * Creates new form MenuPrincipalFuncionario
     */
    public MenuPrincipalFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        painelFundo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbCadastro = new javax.swing.JMenu();
        miCadCliente = new javax.swing.JMenuItem();
        miCadProduto = new javax.swing.JMenuItem();
        mbRelatorio = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miRelatCliente = new javax.swing.JMenuItem();
        miRelatProduto = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mbVenda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        painelFundo.setBackground(new java.awt.Color(161, 126, 83));
        painelFundo.setBorder(new javax.swing.border.MatteBorder(null));
        painelFundo.setLayout(null);

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Caviar Dreams", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 0));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painelFundo.add(jButton1);
        jButton1.setBounds(10, 250, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensSistema/Padaria_NoBG.png"))); // NOI18N
        painelFundo.add(jLabel1);
        jLabel1.setBounds(60, 30, 320, 210);

        jMenuBar1.setBackground(new java.awt.Color(102, 0, 0));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));

        mbCadastro.setBackground(new java.awt.Color(153, 102, 0));
        mbCadastro.setText("Cadastro");

        miCadCliente.setText("Cliente");
        miCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadClienteActionPerformed(evt);
            }
        });
        mbCadastro.add(miCadCliente);

        miCadProduto.setText("Produto");
        miCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadProdutoActionPerformed(evt);
            }
        });
        mbCadastro.add(miCadProduto);

        jMenuBar1.add(mbCadastro);

        mbRelatorio.setText("Relatório");
        mbRelatorio.add(jSeparator1);

        miRelatCliente.setText("Clientes");
        miRelatCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatClienteActionPerformed(evt);
            }
        });
        mbRelatorio.add(miRelatCliente);

        miRelatProduto.setText("Produtos");
        miRelatProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatProdutoActionPerformed(evt);
            }
        });
        mbRelatorio.add(miRelatProduto);

        jMenuItem2.setText("Vendas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mbRelatorio.add(jMenuItem2);

        jMenuBar1.add(mbRelatorio);

        mbVenda.setText("Vendas");

        jMenuItem1.setText("Registrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mbVenda.add(jMenuItem1);

        jMenuBar1.add(mbVenda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadProdutoActionPerformed
        this.setVisible(false);
        
        CadastrarProduto cadProduto = new CadastrarProduto();
        cadProduto.setVisible(true);
    }//GEN-LAST:event_miCadProdutoActionPerformed

    private void miCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadClienteActionPerformed
        this.setVisible(false);
        
        CadastrarCliente cadCliente = new CadastrarCliente();
        cadCliente.setVisible(true);
    }//GEN-LAST:event_miCadClienteActionPerformed

    private void miRelatClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatClienteActionPerformed
        this.setVisible(false);
        
        ListarClientes listCliente = new ListarClientes();
        listCliente.setVisible(true);
    }//GEN-LAST:event_miRelatClienteActionPerformed

    private void miRelatProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatProdutoActionPerformed
        this.setVisible(false);
        ListarProdutos listProdutos = new ListarProdutos();
        listProdutos.setVisible(true);
    }//GEN-LAST:event_miRelatProdutoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        TelaInicialGUI inicial = new TelaInicialGUI();
        inicial.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      this.setVisible(false);
      RegistrarVendas rgVendas = new RegistrarVendas();
      rgVendas.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setVisible(false);
        ListarVendas vendas = new ListarVendas();
        vendas.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mbCadastro;
    private javax.swing.JMenu mbRelatorio;
    private javax.swing.JMenu mbVenda;
    private javax.swing.JMenuItem miCadCliente;
    private javax.swing.JMenuItem miCadProduto;
    private javax.swing.JMenuItem miRelatCliente;
    private javax.swing.JMenuItem miRelatProduto;
    private javax.swing.JPanel painelFundo;
    // End of variables declaration//GEN-END:variables
}
